[package]
name = "woch"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.4.0-rc.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.3.14"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]

